##
# Create a `.lando.local.yml`1 to override the `name:` value
name: my-laravel-app

##
# Recipe Documentation: https://docs.lando.dev/laravel/getting-started.html
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.2.12'
  via: nginx
  webroot: public
  database: mariadb:10.6
  cache: redis
  xdebug: true

##
# Additional Servicas
services:
  node: # Enable Vite usage within Lando
    type: node:16
    scanner: false
    ports:
      - 3009:3009
    build:
      - npm install

  mailhog: # Add MailHog service
    type: mailhog:v1.0.0
    portforward: false
    hogfrom: # Attach MailHog to the services that will utilize it
      - appserver

  chromedriver: # For Laravel Dusk
    type: compose
    #    app_mount: delegate
    services:
      image: robcherry/docker-chromedriver:latest
      # Required. See Below
      command: /usr/local/bin/supervisord -c /etc/supervisord.conf
      expose:
        - '4444'
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined

##
# Provide custom routing for mailhog
proxy:
  mailhog:
    - mail.lndo.site

##
# Add some shortcuts to our container tools
tooling:
  dev:
    service: node
    cmd: |
      echo "Optionally, Consider setting APP_URL to match your Lando environment within \`.env\`\n\n"
      sleep 1
      APP_URL=$(node -r dotenv/config -e "console.log(typeof process.env.APP_URL === 'undefined' && JSON.parse(process.env.LANDO_INFO).appserver_nginx.urls.filter(url => url.startsWith('https') && url.endsWith('lndo.site/')).at(-1) || process.env.APP_URL)") \
      npm run dev
  build:
    service: node
    cmd: npm run build
  npm:
    service: node
    cmd: npm
  artisan:
    service: appserver
    cmd: php artisan
  pest:
    service: appserver
    cmd: ./vendor/bin/pest
  dusk:
    service: appserver
    cmd: php artisan dusk
